info:
  app:
    name: API Gateway

server:
  port: ${PORT:9090}

zuul:
  sensitive-headers: Cookie, Set-Cookie
  routes:
    ping-service:
      path: /ping/**

---

spring:
  profiles: development

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

debug: true