# ====================================================
# Common properties used by all Microservices
# ====================================================
management:
  context-path: /admin
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
    
    healthcheck:
      enabled: true

  instance:
#    hostname: ${HOST_IP:localhost}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    metadata-map:
      management.context-path: ${management.context-path}